# Generated by Django 4.2.1 on 2023-06-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the consumable.', max_length=30)),
                ('unit', models.CharField(help_text='The unit of the consumable. (e.g. kg, g, l, ml, etc.)', max_length=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='The cost per unit of the consumable.', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Consumables',
            },
        ),
        migrations.CreateModel(
            name='ConsumableInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='The quantity of the consumable.', max_digits=10)),
                ('consumables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.consumable')),
            ],
        ),
    ]
